### ISSUE TITLE
[ISSUE] : The card is overlapping the footer

### ISSUE THREAD

**Issue by saswatsamal** [saswatsamal/coFind#1]
### What is the issue you are facing?
The footer is supposed to be at the bottom-most but the cards are overlapping the footer in mobile view.

### Add any screenshots/gif.
![image](https://user-images.githubusercontent.com/39031660/135670543-3118ce40-005f-449b-8ff3-78b33b5b1045.png)

**Comment by SAHU-01** [comment]
May i resolve the issue?

**Comment by saswatsamal** [comment]
Assigned!
