### ISSUE TITLE
[BUG] Desktop View Explore button issue

### ISSUE THREAD

**Issue by SAHU-01** [saswatsamal/coFind#10]
**Describe the bug**

**To Reproduce**
1. Go to 'landing page'
2. Click on 'explore button'

**Expected behavior**

In desktop view ,despite clicking the explore button it does not show the meet page

**Screenshots**

![image](https://user-images.githubusercontent.com/71656941/135727608-46cad8fa-0f7e-4653-8f87-ceda2b958da1.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] BRave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saswatsamal** [comment]
I've assigned it to you!
