### ISSUE TITLE
[BUG] Back Home button cursor pointer on hover

### ISSUE THREAD

**Issue by Abhijeet-Anand-01** [saswatsamal/coFind#14]
Hello there,
On hovering to "Back Home" button, the cursor pointer shows up when the mouse pointer is at the outer of right side of the button and not in the button itself.

![Screenshot (641)](https://user-images.githubusercontent.com/64329744/135731744-04bf33ec-603b-44d9-a82f-0ad1e5427aa8.png)

It's not looking that great. Need to fix it.
And with that I would also like to add some more styling in that button with some hover effects because as of now it's not looking much attractive.
You can assign this issue to me. 
I'll be happy to help you.
Thanks :)

**Comment by saswatsamal** [comment]
Assigned.
