### ISSUE TITLE
[ENHANCEMENT] Search Functionality

### ISSUE THREAD

**Issue by Sanjana-027** [saswatsamal/coFind#17]
Hello,
When we writing something in input field ,it will automatic trigger filter so, there is no use of  Search button  & Along with this, I'll also like to improve the design of the search input field. 

Thanks

**Comment by saswatsamal** [comment]
Assigned

**Comment by Sanjana-027** [comment]
Bhaiya, This issue is already fixed. please, closed this issue.

**Comment by Sanjana-027** [comment]
This ISSUE is already fix, Please close this issue.
