### ISSUE TITLE
[ENHANCEMENT] Button Styling 

### ISSUE THREAD

**Issue by adarshzpatel** [saswatsamal/coFind#22]
I would like to style the 'Explore' & 'Back Home' button to match the 'Add Participants' button as it will look more cleaner and styling will be more consistent throughout the website.

**Comment by saswatsamal** [comment]
Assigned.

**Comment by adarshzpatel** [comment]
Thanks ✨

**Comment by adarshzpatel** [comment]
Completed , you can close this issue.

**Comment by saswatsamal** [comment]
Cool! 🎉
