### ISSUE TITLE
[ENHANCEMENT] Navbar

### ISSUE THREAD

**Issue by Sanjana-027** [saswatsamal/coFind#26]
Hello,
When we scroll down the content of the website, the Navbar & Card are overlap with each-other ,like in below img:-
![WhatsApp Image 2021-10-05 at 12 59 27 PM](https://user-images.githubusercontent.com/79395290/135980606-6620129c-5259-406d-95f8-9f0e632a19b5.jpeg)

If we put background color ,it will look so nice like in below img:-

![WhatsApp Image 2021-10-05 at 12 59 27 PM (1)](https://user-images.githubusercontent.com/79395290/135980750-bd5e586c-75df-47eb-ba08-ead59eac5d3c.jpeg)

I will like to do this .

Thanks!

**Comment by saswatsamal** [comment]
Nice idea. Go for it. Instead of translucent, make the color dark and opaque.

**Comment by Sanjana-027** [comment]
Yaa sure. 

Thanks!
