### ISSUE TITLE
[FEATURE] Card UI at Meet Page

### ISSUE THREAD

**Issue by SAHU-01** [saswatsamal/coFind#3]
**Is your feature request related to a problem? Please describe.**

The meet page card can have a better ui,as in the sizing and borders can be fixed,right now in the mobile view the card seems to consume all the width,leaving no breathing space!

**Describe the solution you'd like**

working with the length and breadth and adding a border radius would make the card more user friendly and appealing

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/71656941/135672974-c554884e-7dab-467f-a87f-c814ab2a71fe.png)

**Comment by SAHU-01** [comment]
The card has an issue ,when extra content is written it removes the extra content, a flex wrap has to be done across the content section so all the card content is visible and size is not hampered
![image](https://user-images.githubusercontent.com/71656941/135766884-0bda296f-ab8c-4763-b12c-d1f3f982ef74.png)

**Comment by saswatsamal** [comment]
Fixed.
